
services:
  krakend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      micro_service:
        ipv4_address: 172.18.0.6

networks:
  micro_service:
    external: true